import crypto from "node:crypto";
import { query } from "../config/db.js";
import { fail } from "../middleware/error.middleware.js";
import { deleteObject, generateDownloadUrl, generateUploadUrl, objectExists } from "./s3.service.js";
import { safeName } from "../utils/generateKey.js";
import { get as getFolder } from "./folder.service.js";

function maxSize() { return Number(process.env.MAX_FILE_SIZE || 104857600); }
export async function createUpload(userId, input) { if (!input.filename || !input.contentType || !Number.isInteger(input.size) || input.size < 1 || input.size > maxSize()) throw fail("Invalid file details"); if (input.folderId) await getFolder(userId, input.folderId); const inserted = await query("INSERT INTO files (user_id, folder_id, original_name, s3_key, mime_type, size) VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, s3_key", [userId, input.folderId || null, input.filename.trim(), `users/${userId}/files/${crypto.randomUUID()}/${safeName(input.filename)}`, input.contentType, input.size]); const file = inserted.rows[0]; return { fileId: file.id, s3Key: file.s3_key, uploadUrl: await generateUploadUrl(file.s3_key, input.contentType) }; }
export async function complete(userId, id) { const result = await query("SELECT * FROM files WHERE id = $1 AND user_id = $2", [id, userId]); if (!result.rowCount) throw fail("File not found", 404, "NOT_FOUND"); const file = result.rows[0]; if (!(await objectExists(file.s3_key))) throw fail("Uploaded object was not found", 400, "UPLOAD_NOT_FOUND"); await query("UPDATE files SET completed = TRUE, updated_at = NOW() WHERE id = $1", [id]); await query("UPDATE users SET storage_used = storage_used + $1 WHERE id = $2", [file.size, userId]); return { ...file, completed: true }; }
export async function list(userId, folderId, search, page = 1) { const values = [userId]; let where = "user_id = $1 AND completed = TRUE"; if (folderId) { values.push(folderId); where += ` AND folder_id = $${values.length}`; } if (search) { values.push(`%${search}%`); where += ` AND original_name ILIKE $${values.length}`; } const limit = 50; values.push(limit, (page - 1) * limit); const result = await query(`SELECT id, folder_id, original_name, mime_type, size, created_at, updated_at FROM files WHERE ${where} ORDER BY created_at DESC LIMIT $${values.length - 1} OFFSET $${values.length}`, values); return result.rows; }
export async function get(userId, id) { const result = await query("SELECT * FROM files WHERE id = $1 AND user_id = $2 AND completed = TRUE", [id, userId]); if (!result.rowCount) throw fail("File not found", 404, "NOT_FOUND"); return result.rows[0]; }
export async function download(userId, id) { const file = await get(userId, id); return { downloadUrl: await generateDownloadUrl(file.s3_key, file.original_name) }; }
export async function update(userId, id, input) { const file = await get(userId, id); if (input.folderId) await getFolder(userId, input.folderId); const result = await query("UPDATE files SET original_name = COALESCE($1, original_name), folder_id = COALESCE($2, folder_id), updated_at = NOW() WHERE id = $3 AND user_id = $4 RETURNING *", [input.name?.trim() || null, input.folderId || null, id, userId]); return result.rows[0] || file; }
export async function remove(userId, id) { const file = await get(userId, id); await deleteObject(file.s3_key); await query("BEGIN"); try { await query("DELETE FROM files WHERE id = $1 AND user_id = $2", [id, userId]); await query("UPDATE users SET storage_used = GREATEST(storage_used - $1, 0) WHERE id = $2", [file.size, userId]); await query("COMMIT"); } catch (error) { await query("ROLLBACK"); throw error; } }
console.log("Hello World");
